#!/usr/bin/env perl
use strict;
use warnings;
use Switch;
use threads;
use FileHandle;
use IPC::Open2;

my $pid = open2(*Reader, *Writer, "~/src/mplayer/mplayer -slave -nograbpointer -profile streaming " . join(" ", @ARGV));

my $read_thread = threads->new(\&read);
my $write_thread = threads->new(\&write);
my $activate_thread = threads->new(\&activate);
$read_thread->join;
$write_thread->join;
$activate_thread->join;

sub write {
  open(TTY, "+</dev/tty") or die "no tty: $!";
  system "stty cbreak </dev/tty >/dev/tty 2>&1";

  my $cmd;
  while (my $c = getc(TTY)) {
    switch ($c) {
      case "p" { $cmd = "pause" }
      case "q" { $cmd = "quit" }
      case "," { $cmd = "seek -10" }
      case "." { $cmd = "seek +10" }
      case "m" { $cmd = "seek -60" }
      case "/" { $cmd = "seek +60" }
      case "p" { $cmd = "volume 1" }
      case "o" { $cmd = "volume -1" }
      case "h" { $cmd = "get_property path" }
      case "u" { $cmd = "set_menu jump_to" }
      case "k" { $cmd = "pt_step -1" }
      case "j" { $cmd = "pt_step 1" }
      case " " { $cmd = "menu hide" }
      case "i" { $cmd = "menu show" }
      else { next }
    }
    print Writer "$cmd\n";
  }
}

sub read {
  while (my $line = <Reader>) {
    chomp $line;
    if ($line =~ /^Playing (.*)\.$/) {
      my $star = `movie_db get star $1`;
      chomp $star;

      my $count = `movie_db get count $1`;
      chomp $count;
      $count++;
      system("movie_db set count $count $1");

      printf "Now Playing: %s, %s, %d\n", $1, star($star), $count;
    } elsif ($line =~ /^.*ANS_path=(.*)/) {
      my $star = `movie_db get star $1`;
      chomp $star;
      $star++;
      if ($star <= 5) {
        my $referer = `movie_db get referer $1`;
        chomp($referer);
        print "-----\n";
        printf "Add star: %s\n", star($star);
        if ($referer eq "") {
          system("movie_db set star $star $1");
          print "$1\n";
        } else {
          my $matches = `movie_db match referer $referer`;
          foreach my $file (split("\n", $matches)) {
            system("movie_db set star $star $file");
            print "$file\n";
          }
        }
        print "-----\n";
      }
    }
  }
}

sub activate {
  while (1) {
    system "activate.scpt iTerm";
    sleep 1;
  }
}

sub star {
  my $star = shift;

  return "X" x $star;
}
