#!/bin/sh

defaults write com.apple.dashboard devmode YES
defaults write com.apple.Terminal ShowTabBar 1
defaults write com.apple.Terminal AppleShowScrollbars WhenScrolling
defaults write com.jetbrains.intellij ApplePressAndHoldEnabled -bool false
