#!/bin/sh

defaults write com.apple.dashboard devmode YES
defaults write com.apple.Terminal ShowTabBar 1
defaults write com.apple.Terminal AppleShowScrollbars WhenScrolling
defaults write com.jetbrains.intellij ApplePressAndHoldEnabled -bool false
defaults write com.sublimetext.2 ApplePressAndHoldEnabled -bool false
sudo sysctl -w net.inet.tcp.delayed_ack=0
