#!/bin/sh

if [ $# -ne 0 ]; then
  case "`uname`" in
    "Linux")
    xclip $*
    ;;
    "Darwin")
    cat $* | pbcopy
    ;;
  esac
else
  case "`uname`" in
    "Linux")
    xclip
    ;;
    "Darwin")
    pbcopy
    ;;
  esac
fi
