#!/bin/sh

if [ $# -ne 0 ]; then
  case "`uname`" in
    "Linux")
    if [ -f "`which xclip`" ]; then
      xclip $*
    fi
    ;;
    "Darwin")
    cat $* | pbcopy
    ;;
  esac
else
  case "`uname`" in
    "Linux")
    if [ -f "`which xclip`" ]; then
      xclip
    fi
    ;;
    "Darwin")
    pbcopy
    ;;
  esac
fi
