#!/usr/bin/perl

use strict;
use warnings;
use Encode;
use Encode::Guess;
use HTML::TreeBuilder::XPath;

my $xpath = "$ARGV[0]";

my $content = do { local $/; <STDIN> };
my $encode = guess_encoding($content, qw/ euc-jp shiftjis 7bit-jis /);
$content = decode($encode->name, $content) unless (utf8::is_utf8($content));

my $tree = HTML::TreeBuilder::XPath->new;
$tree->parse($content);
my @items = $tree->findnodes($xpath);
my @results = map { encode($encode->name, $_->as_text) } @items;
print join("\n", @results);
