#!/usr/bin/env ruby

require 'xmlrpc/client'
require 'pp'
require 'yaml'

config_file = open("#{ENV['HOME']}/.aria2/config.yaml")
config = YAML::load(config_file.read())
config_file.close()

if %x{ pgrep aria2 }.length == 0 then
  printf "launch aria2\n"
  system("aria2c", "-D", "--enable-xml-rpc=true", "--xml-rpc-user=#{user}", "--xml-rpc-pass=#{pass}")
  sleep(3)
end

client = XMLRPC::Client.new2("http://#{config['user']}:#{config['pass']}@localhost:6800/rpc")

urls = Array.new()
options = Hash.new()

ARGV.each do |arg|
  if /=/ =~ arg then
    opt, value = arg.sub(/^--/, "").split(/=/)
    options[opt] = value
  else
    urls.push(arg)
  end
end

result = client.call("aria2.addUri", urls, options)

pp result
