#!/bin/sh

export LC_ALL=C

opt=""

# set referer
if [ -n "$2" ]; then
  opt="${opt} --referer='$2'"
fi

# set cookie
if [ -n "$3" ]; then
  opt="${opt} --load-cookies='$3'"
fi

# set username/password
if [ -n "$3" ]; then
  opt="${opt} --http-user='$3'"
fi
if [ -n "$4" ]; then
  opt="${opt} --http-pass='$4'"
fi

# set url with authentication
url="`echo $1 | perl -pe 's%(\w+)://(.*@)?(.+)%\1://\3%'`"

# set directory
root_dir=`grep 'dir=' "${HOME}/.aria2/aria2.conf" | perl -pe 's%dir=%%'`
if [ -z "${root_dir}" ]; then
  root_dir="${HOME}/Downloads/aria2"
fi
dir="${root_dir}/`echo $url | perl -pe 's%\w+://(.*)/[^/]*%\1%'`"
opt="${opt} --dir='${dir}'"
mkdir -p "${dir}"


aria2_add_uri ${opt} "${url}"
