#!/usr/bin/env python
import Skype4Py
import time
import sys
import codecs
import skype_tail_config

def handler(msg, event):
	if event == u"RECEIVED":
		for w in skype_tail_config.keywords:
			if msg.Body.find(w) >= 0:
				print "[" + msg.Datetime.strftime("%H:%M") + "] " + msg.Chat.FriendlyName + "\n"
				print msg.FromDisplayName + "\n"
				print msg.Body

def main():
	skype = Skype4Py.Skype()
	skype.Attach()
	skype.OnMessageStatus = handler
	while True:
		time.sleep(1)

sys.stdout = codecs.lookup('utf_8')[-1](sys.stdout)
if __name__ == "__main__":
	main()
