#!/usr/bin/env python
import Skype4Py
import time

def handler(msg, event):
	if event == u"RECEIVED":
		print "[" + msg.Datetime.strftime("%H:%M") + "] " + msg.ChatName + "\n"
		print msg.FromDisplayName + "\n"
		print msg.Body

def main():
	skype = Skype4Py.Skype()
	skype.Attach()
	skype.OnMessageStatus = handler
	while True:
		time.sleep(1)

if __name__ == "__main__":
	main()
