#!/usr/bin/env python
import Skype4Py
import time
import sys
import codecs
import json

class SkypeTail:
	def __init__(self, fname):
		self.skype = Skype4Py.Skype()
		self.skype.Attach()
		self.skype.OnMessageStatus = self.handleMessage
		with open(fname) as f:
			self.cfg = json.load(f, 'utf-8')

	def handleMessage(msg, event):
		if event == u"RECEIVED":
			for c in self.cfg:
				if msg.Body.find(c.keyword) >= 0:
					print self.formatMessage(msg)

	def fortmatMessage(msg):
		format = """[%(date)] %(chatname)
		%(from)
		%(body)"""
		param = { 'date': msg.Datetime.strftime("%H:%M"),
		          'chatname': msg.Chat.FriendlyName,
		          'from': msg.FromDisplayName,
		          'body': msg.Body
		        }
		return format % param

	def run(self):
		while True:
			time.sleep(1)

if __name__ == "__main__":
	sys.stdout = codecs.lookup('utf_8')[-1](sys.stdout)

	if (len(sys.argv) != 2):
		print "Error"
		quit()
	fname = sys.argv[1]

	skypeTail = SkypeTail(fname)
	skypeTail.run()
