liberator.globalVariables.plugin_loader_roots = '~/.vimperator/_plugin/coderepos,~/.vimperator/_plugin/other';
liberator.globalVariables.plugin_loader_plugins = [
    '_libly',
    '_smooziee',
    'appendAnchor',
//   'asdfghjkl',
//   'auto_detect_link',
//   'auto_reload',
//   'auto_source',
//   'bookmarktoolbar-hint',
    'browser_object',
//   'bufferecho',
    'caret-hint',
    'char-hints-mod2',
    'commandBookmarklet',
    'command_menu',
//   'cookie',
    'copy',
//   'cpan-search',
    'delicious_search',
    'direct_bookmark',
    'encodingSwitcherCommand',
//   'every',
//   'exShowElementInfo',
//   'ex_autocmd',
//   'exopen',
    'feedSomeKeys_2',
//   'feeder',
//   'fetchyoutube',
//   'foxytunes',
    'gmperator',
//   'googlekanji',
//   'googlesuggest',
    'growl.css',
//   'gvimail',
    'hd-youkai-youtube',
//   'hidecritter',
//   'highlight',
    'hints-yank-paste',
    'history-search-backward',
//   'i_love_echo',
//   'imageextender',
    'ime_controller',
    'ldrize_cooperation',
    'ldrize_cooperation_fetch_flv',
//   'literal-bmark',
    'lo',
//   'localkeymode',
    'loginManager',
    'maine_coon',
//   'mkcolor',
    'moreqmarks',
    'mouseinspect',
    'migemized_find',
    'migemo_completion',
    'migemo_hint',
//   'migratestatusbar',
    'multi_requester',
    'nextlink',
//   'nicontroller',
    'notifier',
    'observer_growl',
//   'options-migrate-user-pref',
//   'peekpage',
    'pluginManager',
//   'proxy',
//   'refcontrol',
//   'relatedBlogSearch',
    'relative_move',
//   'sbmcommentsviewer',
    'scenario-actor',
    'scroll_div',
//   'speeddial',
//   'spellchecker',
    'splitBrowser',
//   'statstat',
//   'stella',
    'tinymenu',
    'toggler',
    'tombloo',
    'treeStyleTab',
//   'twitter',
//   'uaSwitch',
    'ubiquity',
    'walk-input',
//   'xpath_hint',
    'xpathBlink',
//   'xpcom_inspector',
//   'yetmappings',
//   'youtubeamp',
].join(',');
