brew analytics off

# Make sure using latest Homebrew
update || true

# Update already-installed formula (takes too much time, I will do it manually later)
# upgrade

# Add Repository
tap Homebrew/bundle || true
tap homebrew/versions || true
tap homebrew/services || true
tap homebrew/command-not-found || true
tap caskroom/cask || true
tap caskroom/versions || true
tap caskroom/fonts || true
tap suin/suin || true
tap thefox/brewery || true

# Packages
install embulk || true
install graphviz || true
install ioping || true
install joplin || true # Joplin - a note taking and to-do application with synchronization capabilities for Windows, macOS, Linux, Android and iOS.
# kwm https://github.com/koekeishiya/kwm # Tiling window manager with focus follows mouse for OSX
tap tcnksm/license || true
install license || true
# mcmd http://www.nysol.jp/
install olleolleolle/adr-tools/adr_tools || true
install osquery || true
install phook || true
install stow || true # Organize software neatly under a single directory tree (e.g. /usr/local)
install wine || true

# shell
install tmux || true
install reattach-to-user-namespace || true
tap greymd/tools || true
install tmux-xpanes || true
install wemux || true
install desk || true # A lightweight workspace manager for the shell
install peco || true
install fzf || true
#tap jhawthorn/fzy || true
#install fzy || true
install fpp || true
install itchyny/fillin/fillin || true
install knqyf263/pet/pet || true
install b4b4r07/history/history || true
# qfc https://github.com/pindexis/qfc # Quick Command-line File Completion
install parallel || true
# parallel (rust) https://github.com/mmstick/parallel
install nq || true # Unix command line queue utility
# dgsh https://github.com/dspinellis/dgsh # Shell supporting pipelines to and from multiple processes
# egzact https://github.com/greymd/egzact # Strengthen weak points of the shell
# ctypes.sh https://github.com/taviso/ctypes.sh # A foreign function interface for bash.
install autojump || true
install envchain || true
install direnv || true
install zsh || true
install zsh-completions || true
install fish || true
install bash-completion || true
# bish https://github.com/tdenniston/bish # Bish is a language that compiles to Bash.
#install xonsh || true # Python-ish, BASHwards-compatible shell language and command prompt
install bats || true
install checkbashisms || true
install shellcheck || true
tap nviennot/tmate || true
install tmate || true # Instant terminal sharing
tap yudai/gotty || true
install gotty || true # Share your terminal as a web application
install asciinema || true # Record and share terminal sessions
install screenfetch || true # Generate ASCII art with terminal, shell, and OS info
install --HEAD cema-sp/tap/alacritty || true # https://github.com/jwilm/alacritty # A cross-platform, GPU-accelerated terminal emulator
install --HEAD cema-sp/tap/kitty || true # https://github.com/kovidgoyal/kitty # A modern, hackable, featureful, OpenGL based terminal emulator

# utility
install coreutils || true
install lv || true
install jless || true
install lnav || true
install tavianator/tap/bfs || true # A breadth-first version of the UNIX find command
install ripgrep || true
#install ack || true # use ripgrep
install ag || true # use ripgrep
#tap tkengo/highway || true
#install highway || true # use ripgrep
#install sift || true # use ripgrep
#install the_silver_searcher || true # use ripgrep
# icGrep http://parabix.costar.sfu.ca/wiki/ICgrep # The Modern Grep Replacement
install cmigemo || true # Migemo is a tool that supports Japanese incremental search with Romaji
install migemogrep || true
# bingrep https://github.com/m4b/bingrep
install jq || true
tap simeji/jid || true
install jid || true # json incremental digger
tap caius/jo || true
install jo || true # JSON output from a shell
tap tidwall/jd || true
install jd || true # Interactive JSON Editor
install q || true
install xsv || true # A fast CSV toolkit written in Rust.
install saulpw/vd/visidata || true # VisiData (vd on the command-line) is an open-source multitool for interacting with tabular data from within the terminal.
# forest https://github.com/KoharaKazuya/forest
install nkf || true
install tofrodos || true
install ansifilter || true
install lesspipe || true
install rlwrap || true
install extract_url || true
install urlview || true
install progress || true
install pv || true
install pstree || true
install tree || true
install spark || true # Sparklines for the shell
install md5sha1sum || true
install keychain || true
install gpg || true
install gpg2 || true
install pinentry-mac || true
install pwgen || true # Password generator
install gnu-tar || true
install unzip || true
install lha || true
install xz || true
install rename || true
install watch || true
install entr || true # Run arbitrary commands when files change
install watchexec || true
install watchman || true
tap passy/givegif || true
install givegif || true # Find and display GIFs from the command line.
install aspell || true
install fortune || true
tap tldr-pages/tldr || true
install tldr || true # Simplified and community-driven man pages
install cheat || true
install --HEAD motemen/furoshiki2/furoshiki2 || true # furoshiki is a thin wrapper around CUI operation that records command execution results.
install syncthing || true # Open source continuous file synchronization application
install mackup || true # Keep your Mac's application settings in sync
# scat https://github.com/Roman2K/scat # Decentralized, trustless backup tool
install gitfs || true
install terminal-notifier || true # Send macOS User Notifications from the command-line
# alerter https://github.com/vjeantet/alerter
install rcmdnk/rcmdnkpac/parse-plist || true # Parser of plist in OS X.
# yfiton http://yfiton.com/ # Send notifications from the command-line using well-known or modern communication services
# m-cli https://github.com/rgcr/m-cli # Swiss Army Knife for macOS
# mac-cli https://github.com/guarinogabriel/mac-cli # OS X command line tools for developers
# osxlockdown https://github.com/SummitRoute/osxlockdown # Apple OS X tool to audit for, and remediate, security configuration settings.
# osx-config-check https://github.com/kristovatlas/osx-config-check
install argon/mas/mas || true # Mac App Store command line interface

# ssh / remote login
install mobile-shell || true
install MisterTea/et/et || true # Eternal Terminal is a remote shell that automatically reconnects without interrupting the session.
install autossh || true
install pssh || true
install pdsh || true
install sshrc || true
install assh || true
install csshx || true
install kryptco/tap/kr || true # the new home for your SSH private key on your phone
# sekey https://github.com/ntrippar/sekey Use Touch ID / Secure Enclave for SSH Authentication!
install lrzsz || true # Tools for zmodem/xmodem/ymodem file transfer
install knock || true # Port-knock server
install ngrok || true # Secure tunnels to localhost
install tiger-vnc || true

# network
install whois || true
install netcat || true
install socat || true
install tcpdump || true
install ngrep || true
install tcpflow || true
install tcptrace || true
install hping || true
install tcping || true
install tcptraceroute || true
# intrace https://github.com/robertswiecki/intrace # Enumeration of IP hops using existing TCP connections
install httpie || true
install httping || true
install httpry || true
install httpstat || true
install nghttp2 || true
install openssl || true
install nmap || true
install sslscan || true
# nessus http://www.tenable.com/products/nessus-vulnerability-scanner
install jmeter || true
install http_load || true
install wrk || true
install iperf3 || true
install ipcalc || true
install grepcidr || true
install curl || true
install wget || true
install axel || true # Light UNIX download accelerator
install rsync || true
install unison || true
install sslh || true # Applicative Protocol Multiplexer (e.g. share SSH and HTTPS on the same port)
install mitmproxy || true

# browser / client
install w3m || true
# uzbl https://github.com/uzbl/uzbl # A web browser that adheres to the unix philosophy.
install chrome-cli || true
install phantomjs || true
install casperjs || true
install neomutt/homebrew-neomutt/neomutt || true
install weechat || true
tap browsh-org/homebrew-browsh || true
install browsh || true
# geeknote http://www.geeknote.me/ # Work with Evernote from command line

# development
install mruby || true
install rbenv || true
install ruby-build || true
install rsense || true
install python || true
install python3 || true
install pyenv || true
install pyenv-virtualenv || true
install perl || true
install cpanminus || true
install php72 || true
install boris || true
install nvm || true
install nodebrew || true
install closure-compiler || true
install go --cross-compile-common || true
install jenv || true
install maven || true
install scala || true
install sbt || true
install play || true
install ghc || true
install haskell-platform || true
install haskell-stack || true
install cabal-install || true
install erlang || true
install rust || true
install lua || true
# luakit https://github.com/mason-larobina/luakit
install luarocks || true
install clib || true
install metashell || true
install cppcheck || true
install cscope || true
install yasm || true
install jsonnet || true # https://github.com/google/jsonnet
install cmake || true
install bsdmake || true
install autoconf || true
install automake || true
install pkg-config || true
tap universal-ctags/universal-ctags || true
install universal-ctags || true
# rtags https://github.com/Andersbakken/rtags # A c/c++ client/server indexer for c/c++/objc[++] with integration for Emacs based on clang.
install global --with-exuberant-ctags --with-pygments || true
install homebrew/dupes/gdb || true
install cgdb || true
install valgrind || true
install apple-gcc42 || true
install llvm --with-clang || true
install hg || true
install mercurial || true
tap codeclimate/formulae || true
install codeclimate || true
install plantuml || true
tap itchyny/rexdep || true
install rexdep || true # Roughly extract dependency relation from source code
install icdiff || true # Improved colored diff
install meld || true
tap jingweno/ccat || true
install ccat || true # Like cat but displays content with syntax highlighting
install source-highlight || true
install highlight || true
install redpen || true # Proofreading tool to help writers of technical documentation
tap stepanhruda/tap || true
install ios-simulator-app-installer || true
# anyenv https://github.com/riywo/anyenv
# t2b https://thosakwe.github.io/t2b/
tap facebook/homebrew-fb || true
install xar || true

# git
install git || true
install tig || true
install hub || true
tap thoughtbot/formulae || true
install gitsh || true
install git-secrets || true # Prevents you from committing secrets and credentials into git repositories
install git-lfs || true
install git-secret || true # A bash-tool to store your private data inside a git repository.
install git-forgot || true # A tool to help you avoid forgetting git push/commit.
install gibo || true # Access GitHub's .gitignore boilerplates
install ghi || true # Work on GitHub issues on the command-line
install gist || true # Command-line utility for uploading Gists
#install git-now || true # A temporary commit tool for git
#install git-cal || true # github like contributions calendar on terminal
tap gesquive/git-user https://github.com/gesquive/git-user.git || true
install gesquive/git-user/git-user || true # Git plugin that allows you to save multiple user profiles and set them as project defaults
# whichpr https://github.com/pocke/whichpr

# editor
install macvim --with-lua --with-python3 || true
tap neovim/neovim || true
install --HEAD neovim || true
install emacs || true
#install micro || true
install bvi || true

# image / movie / font
install imagemagick || true
install exiftool || true
install ffmpeg || true
install sox || true # SOund eXchange: universal sound sample translator
install fontforge || true
tap sanemat/font || true
install ricty --powerline --vim-powerline || true

# container
install kubernetes-cli || true
install docker || true
install docker-compose || true
install docker-machine || true
install docker-swarm || true
#install boot2docker || true
install ctop || true
install stern || true
#tap codekitchen/dinghy || true
#install dinghy || true
#install fig || true
install homebrew/head-only/xhyve || true
install linux-noah/noah/noah || true

# monitoring
install htop-osx || true
install iftop || true
install sysdig || true
install smartmontools || true
install snap-telemetry || true
# qira https://github.com/BinaryAnalysisPlatform/qira/ # QEMU Interactive Runtime Analyser
install ccze || true # CCZE is a robust and modular log coloriser, with plugins for apm, exim, fetchmail, httpd, postfix, procmail, squid, syslog, ulogd, vsftpd, xferlog and more.

# database
install mysql || true
install mycli || true
install sqlite || true
install sqlmap || true
# sqlcheck https://github.com/jarulraj/sqlcheck

# server
install packer || true
install ansible || true
tap homebrew/nginx || true
install nginx-full --with-mruby-module || true
install redis || true
install kibana || true
# svsh http://ido50.github.io/Svsh/ # svsh is a command line shell for process supervision suites of the daemontools family.
install awscli || true
install rds-command-line-tools || true
install dynamodb-local || true
install heroku-toolbelt || true
#install akamai || true

# homebrew
tap rcmdnk/file || true
install brew-file || true
install brew-gem || true
install brew-pip || true
tap beeftornado/rmtree || true
install beeftornado/rmtree/brew-rmtree || true
install codefirst/sparkling/brew-sparkling
# whalebrew https://github.com/bfirsh/whalebrew

# .dmg
cask install 1password-cli || true
#cask install accessmenubarapps || true
#cask install adobe-reader || true
cask install alfred || true
# alternote http://alternoteapp.com/
#cask install amethyst || true
cask install anaconda || true
#cask install android-studio || true
# anka https://veertu.com/ankabeta/
cask install appcleaner || true
#cask install appium || true
cask install arduino || true
#cask install asepsis || true
# ATOK Spark https://github.com/JustSystems/ATOK_Spark
cask install atom || true
# automute https://github.com/Lorenzo45/AutoMute
#cask install bartender || true
# bdash https://github.com/bdash-app/bdash
cask install bettertouchtool || true
#cask install betterzipql || true
cask install bitbar || true
# blisk https://blisk.io/
cask install boostnote || true
#cask install cargo || true
#cask install Chromium || true
cask install charles || true
cask install cheatsheet || true
cask install chefdk || true
# Chemrtron https://github.com/cho45/Chemrtron
# clipcard
##cask install clipmenu || true
cask install clipy || true
#cask install cloudytabs || true
cask install coconutbattery || true
#cask install codeplane || true
#cask install commander-one || true
#cask install controlplane || true
#cask install coolterm || true
cask install coteditor || true
#cask install dash || true
cask install dash2 || true
#cask install dat || true # https://datproject.org/
cask install devdocs || true
cask install docker || true
#cask install dotnet-sdk || true
cask install dropbox || true
#cask install easysimbl || true
#tap railwaycat/emacsmacport || true
#cask install emacs-mac || true
cask install evernote || true
cask install exa || true
cask install fiddler || true
#cask install filezilla || true
cask install caskroom/fonts/font-fira-code || true
cask install firefox || true
#cask install flashlight || true
cask install flip4mac || true
cask install fluid || true
cask install flux || true
cask install font-source-han-code-jp || true
cask install fork || true # git-fork
#cask install franz || true
# fuwari https://fuwari-app.com/
cask install geektool || true
#cask install genymotion || true
#cask install gimp || true
#cask install github || true
#cask install github-desktop || true
#cask install gitkraken || true
#cask install gitscout || true
#cask install gitup || true
##cask install goofy || true
cask install google-backup-and-sync || true
cask install google-chrome || true
cask install google-drive-file-stream || true
cask install google-japanese-ime || true
#cask install google-photos-backup || true
#cask install grandperspective || true
cask install growlnotify || true
cask install hammerspoon || true
#cask install haroopad || true
#cask install hipchat || true
#cask install hocus-focus || true
#cask install hoster || true
#cask install hosts || true
#cask install hyper || true
#cask install hyperswitch || true
#cask install imageoptim || true
# insomnia https://insomnia.rest/
#cask install insomniax || true
#cask install intel-power-gadget || true
cask install intellij-idea || true
cask install iterm2 || true
cask install iterm2-beta || true
#cask install jadengeller-helium || true
#cask install Jasper || true
cask install java || true
#cask install julia || true
#cask install karabiner-elements || true
#cask install kdiff3 || true
cask install keybase || true
cask install kindle || true
#cask install kitematic || true
#cask install kobito || true
#cask install krita || true
#tap jimbojsb/launchrocket || true
#cask install launchrocket || true
#cask install libreoffice || true
#cask install licecap || true
#cask install limechat || true
#cask install loading || true
#tap aereal/mackerelappactivity || true
#cask install mackerelappactivity || true
#cask install macs-fan-control || true
#cask install manuscripts || true
#cask install media-converter || true
cask install minikube || true
# mockoon https://mockoon.com/ Mock servers in seconds
# monosnap https://monosnap.com/
#cask install mou || true
cask install mysql-workbench || true
#cask install node-webkit-32bit || true
##cask install notifyr || true
cask install omnifocus || true
#cask install onyx || true
#cask install osxfuse || true
#cask install owasp-zap || true
#cask install p4merge || true
#cask install phoenix || true # A lightweight macOS/OS X window and app manager scriptable with JavaScript
#cask install powershell || true
#cask install qlcolorcode || true
#cask install qlmarkdown || true
#cask install qlstephen || true
#cask install quicklook-csv || true
#cask install quicklook-json || true
# quitter https://marco.org/apps#quitter
# quiver https://github.com/HappenApps/Quiver
# remixos http://www.jide.com/en/remixos
#cask install rightfont || true
# riverflow http://questbe.at/riverflow/
#cask install rstudio || true
# screentime https://github.com/nst/ScreenTime
#cask install sequel-pro || true
#cask install seil || true
#cask install shiori || true
cask install skim || true
##cask install skitch || true
#cask install skype || true
# sikuli https://github.com/sikuli/sikuli
tap dteoh/sqa || true
cask install slowquitapps || true
#cask install sourcetree || true
#cask install spectacle || true
#cask install sqlitebrowser || true
#cask install startninja || true
##cask install sublime-text || true
#cask install td-agent || true
#cask install textbar || true
#cask install textexpander || true
#cask install the-unarchiver || true
# Tickeys https://github.com/yingDev/Tickeys
#cask install tinkertool || true
# Trace Compass http://tracecompass.org/ Eclipse Trace Compass is an open source application for viewing and analyzing any type of logs or traces.
#cask install totalfinder || true
#cask install totalspace || true
##cask install totalterminal || true
cask install trailer || true
#cask install typora || true
#cask install unicorns || true
#cask install utorrent || true
cask install vagrant || true
cask install vagrant-manager || true
#cask install vault || true
# veertu http://veertu.com/
cask install virtualbox || true
#cask install visual-studio || true
cask install visual-studio-code || true
#cask install visualvm || true
#cask install vivaldi || true
cask install vlc || true
# wallcat https://www.wall.cat
cask install wireshark || true
#cask install xamarin-studio || true
cask install xmind || true
cask install xquartz || true
#cask install xtrafinder || true
#cask install yujitach-menumeters || true

# Remove outdated versions
cleanup
