# Make sure using latest Homebrew
update || true

# Update already-installed formula (takes too much time, I will do it manually later)
# upgrade

# Add Repository
tap homebrew/versions || true
tap phinze/homebrew-cask || true
tap homebrew/binary || true
tap jimbojsb/launchrocket || true

# Packages
install ack || true
install ag || true
install apple-gcc42 || true
install aspell || true
install autojump || true
install automake || true
install autossh || true
install boot2docker || true
install bsdmake || true
install casperjs || true
install cgdb || true
install closure-compiler || true
install cmake || true
install cmigemo || true
install cscope || true
install ctags || true
install curl || true
install docker || true
install emacs || true
install erlang || true
install exiftool || true
install ffmpeg || true
install fish || true
install fortune || true
install ghc || true
install gibo || true
install gist || true
install git || true
install global || true
install go || true
install graphviz || true
install haskell-platform || true
install heroku-toolbelt || true
install hg || true
install hping || true
install hub || true
install imagemagick || true
install jq || true
install keychain || true
install llvm --with-clang || true
install lua || true
install lv || true
install macvim --HEAD --with-lua || true
install meld || true
install mobile-shell || true
install mysql || true
install ngrep || true
install nkf || true
install phantomjs || true
install play || true
install pv || true
install python3 || true
install rbenv || true
install reattach-to-user-namespace || true
install redis || true
install rlwrap || true
install ruby-build || true
install sbt || true
install scala || true
install spark || true
install sqlite || true
install stow || true
install the_silver_searcher || true
install tig || true
install tmux || true
install tree || true
install w3m || true
install wemux || true
install wget || true
install zsh || true
install zsh-completions || true

# .dmg
install brew-cask || true
#cask install alfred || true
#cask install appcleaner || true
#cask install bettertouchtool || true
#cask install Chromium || true
#cask install coteditor || true
#cask install dash || true
#cask install dropbox || true
#cask install evernote || true
#cask install firefox || true
#cask install flip4mac || true
#cask install gimp || true
#cask install github || true
#cask install google-chrome || true
#cask install google-drive || true
#cask install hipchat || true
#cask install iterm2 || true
#cask install keyremap4macbook || true
#cask install kindle || true
#cask install launchrocket || true
#cask install libreoffice || true
#cask install limechat || true
#cask install mysql-workbench || true
#cask install p4merge || true
#cask install rstudio || true
#cask install skitch || true
#cask install sourcetree || true
#cask install sublime-text || true
#cask install totalfinder || true
#cask install vagrant || true
#cask install virtualbox || true
#cask install vlc || true
#cask install wireshark || true
#cask install xamarin-studio || true
#cask install xquartz || true

# Remove outdated versions
cleanup
