# Make sure using latest Homebrew
update || true

# Update already-installed formula (takes too much time, I will do it manually later)
# upgrade

# Add Repository
tap Homebrew/brewdler || true
tap Homebrew/bundle || true
tap homebrew/versions || true
tap homebrew/dupes || true
tap caskroom/cask || true
tap caskroom/versions || true
tap phinze/homebrew-cask || true
tap homebrew/binary || true
tap Homebrew/brewdler || true
#tap homebrew/boneyard || true
tap jimbojsb/launchrocket || true
tap thoughtbot/formulae || true
tap railwaycat/emacsmacport || true
tap sanemat/font || true
tap suin/suin || true
tap rcmdnk/file || true
tap peco/peco || true
tap caskroom/fonts || true
tap stepanhruda/tap || true
tap jingweno/ccat || true
tap nviennot/tmate || true
tap codeclimate/formulae || true
tap homebrew/head-only || true
tap tcnksm/license || true
tap universal-ctags/universal-ctags || true
tap neovim/neovim || true
tap yudai/gotty || true
tap tkengo/highway || true
tap beeftornado/rmtree || true
tap itchyny/rexdep || true
tap tldr-pages/tldr || true
tap homebrew/nginx || true
tap codekitchen/dinghy || true
tap caskroom/cask || true
tap caius/jo || true
tap passy/givegif || true
tap homebrew/services || true
tap jhawthorn/fzy || true

# Packages
install ack || true
install ag || true
install ansible || true
# anyenv https://github.com/riywo/anyenv
install apple-gcc42 || true
install asciinema || true
install aspell || true
install assh || true
install autoconf || true
install autojump || true
install automake || true
install autossh || true
install awscli || true
install bash-completion || true
install bats || true
install beeftornado/rmtree/brew-rmtree || true
# bish https://github.com/tdenniston/bish
install boot2docker || true
install boris || true
install brew-file || true
install brew-gem || true
install brew-pip || true
install bsdmake || true
install casperjs || true
install ccat || true
install ccze || true
install cgdb || true
install checkbashisms || true
install chrome-cli || true
install clib || true
install closure-compiler || true
install cmake || true
install cmigemo || true
install codeclimate || true
install codefirst/sparkling/brew-sparkling
install coreutils || true
install cpanminus || true
install cppcheck || true
install cscope || true
install csshx || true
# ctypes.sh https://github.com/taviso/ctypes.sh
install curl || true
install dinghy || true
install direnv || true
install docker || true
install docker-compose || true
install docker-machine || true
install docker-swarm || true
install dynamodb-local || true
# egzact https://github.com/greymd/egzact
install emacs || true
install embulk || true
install entr || true
install envchain || true
install erlang || true
install exiftool || true
install ffmpeg || true
install fig || true
install fish || true
install fontforge || true
install fortune || true
install fpp || true
install fzf || true
install fzy || true
# geeknote http://www.geeknote.me/
install homebrew/dupes/gdb || true
install homebrew/head-only/xhyve || true
install ghc || true
install ghi || true
install gibo || true
install gist || true
install git || true
install git-cal || true
install git-forgot || true
install git-lfs || true
install git-now || true
install git-secrets || true
install gitsh || true
install givegif || true
install global --with-exuberant-ctags --with-pygments || true
install gnu-tar || true
install go --cross-compile-common || true
install gotty || true
install gpg || true
install graphviz || true
install grepcidr || true
install haskell-platform || true
install heroku-toolbelt || true
install hg || true
install highlight || true
install highway || true
install hping || true
install htop-osx || true
install http_load || true
install httpie || true
install httping || true
install httpry || true
install hub || true
install icdiff || true
# icGrep http://parabix.costar.sfu.ca/wiki/ICgrep
install iftop || true
install imagemagick || true
# intrace https://github.com/robertswiecki/intrace
install ios-simulator-app-installer || true
install jless || true
install jmeter || true
install jo || true
install ipcalc || true
install iperf3 || true
install jq || true
# jsonnet https://github.com/google/jsonnet
install keychain || true
install kibana || true
# kwm https://github.com/koekeishiya/kwm
install lesspipe || true
install lha || true
install license || true
install llvm --with-clang || true
install lnav || true
install lrzsz || true
install lua || true
# luakit https://github.com/mason-larobina/luakit
install luarocks || true
install lv || true
# m-cli https://github.com/rgcr/m-cli
# mac-cli https://github.com/guarinogabriel/mac-cli
install macvim --HEAD --with-lua || true
install mackup || true
install argon/mas/mas || true
install maven || true
install md5sha1sum || true
install meld || true
install mercurial || true
install metashell || true
install micro || true
install migemogrep || true
install mobile-shell || true
install mruby || true
install mycli || true
install mysql || true
install neomutt/homebrew-neomutt/neomutt || true
install --HEAD neovim || true
# nessus http://www.tenable.com/products/nessus-vulnerability-scanner
install netcat || true
install nghttp2 || true
install nginx-full --with-mruby-module || true
install ngrok || true
install nkf || true
install nmap || true
install ngrep || true
install nkf || true
install nodebrew || true
install nq || true
install nvm || true
install openssl || true
install osquery || true
# osxlockdown https://github.com/SummitRoute/osxlockdown
install packer || true
install parallel || true
install peco || true
install phantomjs || true
install pkg-config || true
install plantuml || true
install play || true
install progress || true
install pssh || true
install pstree || true
install pv || true
install pwgen || true
install pyenv || true
install pyenv-virtualenv || true
install python || true
install python3 || true
install pyenv || true
install pyenv-virtualenv || true
install q || true
# qfc https://github.com/pindexis/qfc
# qira https://github.com/BinaryAnalysisPlatform/qira/
install rbenv || true
install rcmdnk/file/brew-file || true
install rcmdnk/rcmdnkpac/parse-plist || true
install rds-command-line-tools || true
install reattach-to-user-namespace || true
install redis || true
install redpen || true
install rexdep || true
install ricty --powerline --vim-powerline || true
install https://raw.githubusercontent.com/BurntSushi/ripgrep/master/pkg/brew/ripgrep.rb || true
install rlwrap || true
install rsense || true
install ruby-build || true
install rust || true
install sbt || true
install scala || true
install screenfetch || true
install shellcheck || true
install sift || true
install smartmontools || true
install socat || true
install source-highlight || true
install sox || true
#install spark || true
install sqlite || true
install sshrc || true
install sslh || true
install sslscan || true
install stow || true
# svsh http://ido50.github.io/Svsh/
install syncthing || true
install sysdig || true
install tcpflow || true
install tcptrace || true
install terminal-notifier || true
install the_silver_searcher || true
install tig || true
install tiger-vnc || true
install tldr || true
install tmate || true
install tmux || true
install tofrodos || true
install tree || true
install unison || true
install universal-ctags || true
install unzip || true
# uzbl https://github.com/uzbl/uzbl
install valgrind || true
install w3m || true
install weechat || true
install wemux || true
install wget || true
install whois || true
install wine || true
install wrk || true
install xonsh || true
install xz || true
install yasm || true
# yfiton http://yfiton.com/
install zsh || true
install zsh-completions || true

# .dmg
#cask install accessmenubarapps || true
#cask install adobe-reader || true
#cask install alfred || true
# alternote http://alternoteapp.com/
#cask install amethyst || true
#cask install android-studio || true
#cask install appcleaner || true
#cask install appium || true
#cask install asepsis || true
#cask install atom || true
# automute https://github.com/Lorenzo45/AutoMute
#cask install bartender || true
#cask install bettertouchtool || true
#cask install betterzipql || true
#cask install bitbar || true
# blisk https://blisk.io/
# boost http://b00st.io/
#cask install cargo || true
#cask install Chromium || true
#cask install charles || true
#cask install cheatsheet || true
#cask install chefdk || true
# Chemrtron https://github.com/cho45/Chemrtron
# clipcard
#cask install clipmenu || true
#cask install clipy || true
#cask install cloudytabs || true
#cask install coconutbattery || true
#cask install codeplane || true
#cask install commander-one || true
#cask install controlplane || true
#cask install coolterm || true
#cask install coteditor || true
#cask install dash || true
#cask install dash2 || true
#cask install docker || true
#cask install dropbox || true
#cask install easysimbl || true
#cask install evernote || true
#cask install exa || true
#cask install fiddler || true
#cask install firefox || true
#cask install flashlight || true
#cask install flip4mac || true
#cask install fluid || true
#cask install flux || true
#cask install font-source-han-code-jp || true
#cask install franz || true
#cask install geektool || true
#cask install genymotion || true
#cask install gimp || true
#cask install github || true
#cask install goofy || true
#cask install google-chrome || true
#cask install google-drive || true
#cask install google-japanese-ime || true
#cask install google-photos-backup || true
#cask install grandperspective || true
#cask install growlnotify || true
#cask install hammerspoon || true
#cask install haroopad || true
#cask install hipchat || true
#cask install hocus-focus || true
#cask install hoster || true
#cask install hosts || true
#cask install hyperswitch || true
#cask install imageoptim || true
# insomnia https://insomnia.rest/
#cask install insomniax || true
#cask install intel-power-gadget || true
#cask install intellij-idea || true
#cask install iterm2 || true
#cask install iterm2-beta || true
#cask install jadengeller-helium || true
#cask install java || true
#cask install julia || true
#cask install karabiner || true
#cask install kdiff3 || true
#cask install kindle || true
#cask install kitematic || true
#cask install kobito || true
#cask install krita || true
#cask install launchrocket || true
#cask install libreoffice || true
#cask install licecap || true
#cask install limechat || true
#cask install loading || true
#cask install macs-fan-control || true
#cask install manuscripts || true
#cask install media-converter || true
# monosnap https://monosnap.com/
#cask install mou || true
#cask install mysql-workbench || true
#cask install node-webkit-32bit || true
#cask install notifyr || true
#cask install omnifocus || true
#cask install onyx || true
#cask install owasp-zap || true
#cask install p4merge || true
#cask install powershell || true
#cask install qlcolorcode || true
#cask install qlmarkdown || true
#cask install qlstephen || true
#cask install quicklook-csv || true
#cask install quicklook-json || true
# quitter https://marco.org/apps#quitter
# quiver https://github.com/HappenApps/Quiver
# remixos http://www.jide.com/en/remixos
#cask install rightfont || true
# riverflow http://questbe.at/riverflow/
#cask install rstudio || true
# screentime https://github.com/nst/ScreenTime
#cask install sequel-pro || true
#cask install seil || true
#cask install shiori || true
#cask install skim || true
#cask install skitch || true
# sikuli https://github.com/sikuli/sikuli
#cask install sourcetree || true
#cask install spectacle || true
#cask install sqlitebrowser || true
#cask install startninja || true
#cask install sublime-text || true
#cask install td-agent || true
#cask install textbar || true
#cask install textexpander || true
#cask install the-unarchiver || true
# Tickeys https://github.com/yingDev/Tickeys
#cask install tinkertool || true
#cask install totalfinder || true
#cask install totalspace || true
#cask install totalterminal || true
#cask install trailer || true
#cask install typora || true
#cask install unicorns || true
#cask install utorrent || true
#cask install vagrant || true
#cask install vagrant-manager || true
#cask install vault || true
# veertu http://veertu.com/
#cask install virtualbox || true
#cask install visual-studio-code || true
#cask install vlc || true
# wallcat https://www.wall.cat
#cask install wireshark || true
#cask install xamarin-studio || true
#cask install xmind || true
#cask install xquartz || true
#cask install xtrafinder || true
#cask install yujitach-menumeters || true

# pip
pip install diff-highlight

# Remove outdated versions
cleanup
