#!/bin/sh

go get code.google.com/p/go.tools/cmd/goimports
go get code.google.com/p/go.tools/cmd/godoc
go get code.google.com/p/go.tools/cmd/vet
go get code.google.com/p/go.tools/cmd/cover
go get github.com/nsf/gocode
go get github.com/golang/lint
go get code.google.com/p/rog-go/exp/cmd/godef
go get github.com/jstemmer/gotags
go get install github.com/tcnksm/dmux
go get github.com/mattn/gof
go get github.com/motemen/github-commit-status-mark
go get github.com/handlename/go-get-git-ignore
