#!/bin/sh

go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/godoc
go get -u golang.org/x/tools/cmd/vet
go get -u golang.org/x/tools/cmd/cover
go get -u github.com/nsf/gocode
go get -u github.com/golang/lint/golint
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/jstemmer/gotags
go get -u github.com/tcnksm/dmux
go get -u github.com/mattn/gof
go get -u github.com/motemen/github-commit-status-mark
go get -u github.com/handlename/go-get-git-ignore
go get -u github.com/motemen/gore
go get -u github.com/motemen/go-quickfix/cmd/goquickfix
go get -u github.com/k0kubun/pp
go get -u github.com/tools/godep
go get -u github.com/gizak/termui
go get -u github.com/motemen/ghq
go get -u github.com/jgrahamc/httpdiff
go get -d github.com/tcnksm/go-latest
go get -u github.com/motemen/hub-pr
go get -u github.com/mailgun/godebug
go get -u github.com/b4b4r07/gomi
go install github.com/ncw/rclone
go get github.com/dufferzafar/cheat
go get github.com/monochromegane/mdt
