;; load-after-bytecompile
;; http://www.bookshelf.jp/cgi-bin/goto.cgi?file=meadow&node=my-load
(require 'bytecomp)
(require 'path-util)
(defun load-after-bytecompile (file)
  (let ((compiled-file-name ""))
    (if (not (string-match "\\.el$" file))
        (setq file (concat file ".el")))
    (setq file (file-installed-p file))
    (setq compiled-file-name (byte-compile-dest-file file))
    (if (file-installed-p compiled-file-name)
        (if (file-newer-than-file-p compiled-file-name file)
            (load-file compiled-file-name)
          (if (byte-compile-file file t)
              ()
            (error "Can't compile"))
          )
      (if (byte-compile-file file t)
          ()
        (error "Can't compile"))
      )))
