#!/bin/sh

defaults write -g InitialKeyRepeat -int 11
defaults write -g KeyRepeat -int 1
defaults write com.apple.dashboard devmode YES
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write com.apple.finder FinderSounds -bool no
defaults write com.apple.finder QLEnableTextSelection -bool true
defaults write com.apple.Terminal ShowTabBar 1
defaults write com.apple.Terminal AppleShowScrollbars WhenScrolling
defaults write com.jetbrains.intellij ApplePressAndHoldEnabled -bool false
defaults write com.sublimetext.2 ApplePressAndHoldEnabled -bool false
sudo sysctl -w net.inet.tcp.delayed_ack=0

pushd .
git clone https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard.git && cd tmux-MacOSX-pasteboard && make && cp reattach-to-user-namespace ~/bin/tmux
popd
rm -rf tmux-MacOSX-pasteboard

# Homebrew
if [ ! -x "`which brew`" ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
fi
brew install ack
brew install autossh
brew install exiftool
brew install git
brew install global
brew install jq
brew install lv
brew install macvim --with-lua
brew install mobile-shell
brew install ngrep
brew install nkf
brew install sqlite
brew install the_silver_searcher
brew install tmux
brew install w3m
brew install wget
brew install zsh
