#!/bin/sh

export __CF_USER_TEXT_ENCODING="`printf "%#x\n" ${UID}`:0x8000100:14"

if [ $# -ne 0 ]; then
  if [ -f "${HOME}/bin/.cbcopy_remote" ]; then
    cat $* | nc -q1 localhost 2224
  else
    case "`uname`" in
      "Linux")
      if [ -f "`which xclip`" ]; then
        xclip $*
      fi
      ;;
      "Darwin")
      cat $* | pbcopy
      ;;
    esac
  fi
else
  if [ -f "${HOME}/bin/.cbcopy_remote" ]; then
    cat | nc -q1 localhost 2224
  else
    case "`uname`" in
      "Linux")
      if [ -f "`which xclip`" ]; then
        xclip
      fi
      ;;
      "Darwin")
      pbcopy
      ;;
    esac
  fi
fi
