#!/bin/sh

export __CF_USER_TEXT_ENCODING="`printf "%#x\n" ${UID}`:0x8000100:14"

case "`uname`" in
  "Linux")
  if [ -f "`which xclip`" ]; then
    xsel -b -o
  fi
  ;;
  "Darwin")
  pbpaste
  ;;
esac
