#!/usr/bin/env ruby

require 'xmlrpc/client'
require 'pp'
require 'yaml'
require 'sqlite3'
require 'pathname'

config_file = open("#{ENV['HOME']}/.aria2/config.yaml")
config = YAML::load(config_file.read())
config_file.close()

gid = ARGV[0]
Dir.chdir("#{config['dir']}")

client = XMLRPC::Client.new2("http://#{config['user']}:#{config['pass']}@localhost:6800/rpc")

result = client.call("aria2.tellStatus", gid)
status = result['status']

result = client.call("aria2.getFiles", gid)
for file in result.collect {|x| x['path']}
  # temporaliry patch
  uri = file.sub(/.*aria2\//, "http://")

  system("download_db status #{uri} #{status}")

  if status == "complete" then
    path = "./" + Pathname.new(file).relative_path_from(Pathname.new(config['dir'])).to_s
    db = SQLite3::Database.new("movies.db")
    row = db.execute("select referer from download where uri = '#{uri}'")
    db.close
    for f in `extract -d -o #{path}` do
      system("movie_db add #{f}")
      system("movie_db set referer #{row[0]} #{f}")
    end
  end
end
