(require 'emms-setup nil t)
(require 'emms-i18n nil t)
(emms-standard)
(emms-default-players)
(setq emms-repeat-playlist t)
(setq emms-player-list '(emms-player-mplayer))
(setq emms-source-file-default-directory "~/Music/")
