;; http://howm.sourceforge.jp/
(my-autoload-and-when 'howm-menu "howm"
                      (setq howm-menu-lang 'ja)
                      (setq howm-directory "~/howm")
                      (setq howm-file-name-format "%Y/%m/%Y%m%d-%H%M%S.howm")
                      (setq howm-keyword-file "~/howm/.howm-keys")
                      (setq howm-history-file "~/howm/.howm-history")
                      (setq howm-menu-file "~/howm/.howm-menu")
                      (setq howm-keyword-case-fold-search t)
                      (setq howm-list-title nil)
                      (setq howm-menu-refresh-after-save nil)
                      (setq howm-refresh-after-save nil)
                      (setq howm-menu-expiry-hours 2)
                      (setq howm-view-grep-command "egrep")
                      )
(global-set-key "\C-c,," 'howm-menu)
