;; dirvars (set directory local variables)
;(install-elisp "http://www.bookshelf.jp/elc/dirvars.el")
(require 'dirvars)

;; diminish
;(install-elisp "http://www.eskimo.com/~seldon/diminish.el")
(require 'diminish)
;(diminish 'emacs-lisp-mode "Elisp")
(diminish 'widen-window-mode " WW")
;(diminish 'cwarn-mode)
(diminish 'doxymacs-mode)
(diminish 'eldoc-mode)
;(diminish 'gtags-mode)
(diminish 'flymake-mode)
(diminish 'hs-minor-mode)
(diminish 'my-keyjack-mode)
(diminish 'yas/minor-mode)
