liberator.globalVariables.plugin_loader_roots = '~/.vimperator/_plugin/coderepos,~/.vimperator/_plugin/coderepos/notifier,~/.vimperator/_plugin/vimperator,~/.vimperator/_plugin/other,~/.vimperator/_plugin/my,~/.vimperator/_plugin/local';
liberator.globalVariables.plugin_loader_plugins = [
    'observer_growl',
    'subject_weather_yahoo',
    '_libly',
    '_smooziee',
    'account_switcher',
    'alert',
//  'alias',
    'amazon_simple_uri',
    'appendAnchor',
    'applauncher',
    'auto-focus-frame',
    'auto_reload',
    'auto_source',
    'auto_word_select_mode',
    'browser_object',
    'bufferecho',
    'caret-hint',
    'char-hints-mod2',
    'commandBookmarklet',
    'cookie',
    'cookieManager',
    'copy',
    'cpan-search',
    'delicious_search',
    'direct_bookmark',
    'encodingSwitcherCommand',
    'exShowElementInfo',
//  'feedSomeKeys_2',
    'feedSomeKeys_3',
    'feeder',
    'fetchyoutube',
//  'forcefocuscontent',
    'gmperator',
//  'hatebuCounter',
    'hatena-bookmark-search',
    'hd-youkai-youtube',
    'highlight',
    'hint-tombloo',
    'hints-for-embedded',
    'hints-yank-paste',
    'history-search-backward',
    'i_love_echo',
    'ime_controller',
    'ldrize_cooperation',
    'ldrize_cooperation_fetch_flv',
    'lo',
    'localkeymode',
    'loginManager',
    'maine_coon',
//  'marker_reader',
    'migemo-find',
//  'migemized_find',
    'migemo_completion',
//  'migemo_hint',
    'migratestatusbar',
    'moreqmarks',
    'mouseinspect',
    'multi_requester',
    'nextlink',
//  'nicontroller',
    'nnp_cooperation',
    'notifier',
    'opener',
    'opener-ex',
    'options-migrate-user-pref',
    'option-selector',
    'pluginManager',
    'readcatlater',
    'relative_move',
//  'reporter',
    'resizable_textarea',
    'sbmcommentsviewer',
    'scenario-actor',
    'scroll_div',
    'spatial-navigation',
    'splitBrowser',
    'stella',
    'tabsort',
    'tinymenu',
    'toggler',
    'tombloo',
    'treeStyleTab',
    'ubiquity',
    'video-controller',
    'walk-input',
    'x-hint',
    'xpathBlink',
    'yetmappings',
//  'youtubeamp',
//  'zip-de-download',
    'firebug',
    'link-targets',
    'logintumblr',
    'set_tumblr_channel_id',
    'multipleTabHandler',
    'treeStyleTab',
].join(',');
