#!/bin/sh

export LC_ALL=C

while getopts "e" flag; do
  case ${flag} in
    \?) OPT_ERROR=1; break;;
    e) opt_e=true;;
  esac
done

shift $(( $OPTIND - 1 ))

if [ $OPT_ERROR ]; then
  echo >&2 "Error."
  exit 1
fi


aria2_opt=""
url="`echo $1 | perl -pe 's%(\w+)://(.*@)?(.+)%\1://\3%'`" # remove pre-embedded authentication
referer="$2"
user="$3"
pass="$4"

root_dir=`grep 'dir=' "${HOME}/.aria2/aria2.conf" | perl -pe 's%dir=%%'`
if [ -z "${root_dir}" ]; then
  root_dir="${HOME}/Downloads/aria2"
fi
dir="${root_dir}/`echo $url | perl -pe 's%\w+://(.*)/[^/]*%\1%'`"


# register information to DB
cd ${root_dir}
result=`download_db register ${url} ${referer} ${user} ${pass}`
if [ "${result}" = "Duplicated." ]; then
  echo >&2 "Skip: same url."
  exit 1
fi
filename=`echo ${url} | perl -pe "s%.*/(.*)%\1%"`
registered=`sqlite3 ${HOME}/Downloads/aria2/movies.db "select * from download where referer = '${referer}'" | grep ${filename} | wc -l`
if [ "${registered}" -gt 1 ]; then
  download_db status ${url} 'ignore'
  echo >&2 "Skip: same file."
  exit 1
fi
