#!/usr/bin/env ruby

require 'xmlrpc/client'
require 'pp'
require 'yaml'

config_file = open("#{ENV['HOME']}/.aria2/config.yaml")
config = YAML::load(config_file.read())
config_file.close()

gid = ARGV[0]

client = XMLRPC::Client.new2("http://#{config['user']}:#{config['pass']}@localhost:6800/rpc")

result = client.call("aria2.tellStatus", gid)
status = result['status']

result = client.call("aria2.getFiles", gid)
for file in result.collect {|x| x['path']}
  # temporaliry patch
  uri = file.sub(/.*aria2\//, "http://")
  Dir.chdir("#{ENV['HOME']}/Downloads/aria2")

  system("download_db status #{uri} #{status}")
end

if status == "complete" then
  system("on_download_complete -d -o #{file}")
end
